l1_cross_domain_messenger: [1.4.1, 1.6.0, 2.1.1, 2.3.0]
l1_erc721_bridge: [1.1.2, 1.3.0, 2.1.0]
l1_standard_bridge: [1.1.1, 1.4.0, 2.1.0]
l2_output_oracle: [1.3.1, 1.5.0, 1.8.0]
optimism_mintable_erc20_factory: [1.1.1, 1.4.0, 1.9.0]
optimism_portal: [1.7.2, 1.9.0, 3.3.0]
system_config: [1.3.1, 1.7.0, 1.12.0]

# superchain-wide contracts
protocol_versions: [1.0.0]
superchain_config: [1.1.0]
