name: Mainnet
l1:
  chain_id: 1
  public_rpc: https://ethereum-mainnet-rpc.allthatnode.com
  explorer: https://etherscan.io

protocol_versions_addr: "0x8062AbC286f5e7D9428a0Ccb9AbD71e50d93b935"
superchain_config_addr: "0x95703e0982140d16f8eba6d158fccede42f04a4c"

